# Generated by Django 3.0.5 on 2020-05-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='sector',
            field=models.CharField(blank=True, choices=[('sur', 'Sur'), ('sur_e', 'Sur-Este'), ('cen', 'Centro'), ('nor', 'Norte'), ('samb', 'Samborondon')], max_length=50, verbose_name='sector'),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default=2, max_length=10, verbose_name='telefono'),
            preserve_default=False,
        ),
    ]
